// Generated by CIRCT firtool-1.48.0-34-g7018fb13b
// external module SB_RAM40_4K

module Top(
  input  [7:0] WDATA,
  input        WE,
               CLK,
  output [7:0] RDATA
);

  wire [15:0] _SB_RAM40_4K_inst0_RDATA;
  SB_RAM40_4K #(
    .WRITE_MODE(1),
    .READ_MODE(1),
    .INIT_0(256'd1431633921),
    .INIT_1(256'd0),
    .INIT_2(256'd0),
    .INIT_3(256'd0),
    .INIT_4(256'd0),
    .INIT_5(256'd0),
    .INIT_6(256'd0),
    .INIT_7(256'd0),
    .INIT_8(256'd0),
    .INIT_9(256'd0),
    .INIT_A(256'd0),
    .INIT_B(256'd0),
    .INIT_C(256'd0),
    .INIT_D(256'd0),
    .INIT_E(256'd0),
    .INIT_F(256'd0)
  ) SB_RAM40_4K_inst0 (
    .RADDR (11'h1),
    .RCLK  (CLK),
    .RCLKE (1'h1),
    .RE    (1'h1),
    .WCLK  (CLK),
    .WCLKE (1'h1),
    .WE    (WE),
    .WADDR (11'h1),
    .MASK  (16'h0),
    .WDATA
      ({1'h0,
        WDATA[7],
        1'h0,
        WDATA[6],
        1'h0,
        WDATA[5],
        1'h0,
        WDATA[4],
        1'h0,
        WDATA[3],
        1'h0,
        WDATA[2],
        1'h0,
        WDATA[1],
        1'h0,
        WDATA[0]}),
    .RDATA (_SB_RAM40_4K_inst0_RDATA)
  );
  assign RDATA =
    {_SB_RAM40_4K_inst0_RDATA[14],
     _SB_RAM40_4K_inst0_RDATA[12],
     _SB_RAM40_4K_inst0_RDATA[10],
     _SB_RAM40_4K_inst0_RDATA[8],
     _SB_RAM40_4K_inst0_RDATA[6],
     _SB_RAM40_4K_inst0_RDATA[4],
     _SB_RAM40_4K_inst0_RDATA[2],
     _SB_RAM40_4K_inst0_RDATA[0]};
endmodule

